# Generated by Django 3.0.5 on 2020-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ticketNo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
