# Generated by Django 3.0.5 on 2020-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200606_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
